@startuml redoxtheme
!$RedoxBlack = "#001f17"

!$RedoxGrey1 = "#4b4d4f"
!$RedoxGrey2 = "#707476"
!$RedoxGrey3 = "#bcc2c6"
!$RedoxGrey4 = "#d7dadd"
!$RedoxGrey5 = "#eaeced"

!$RedoxGrey6 = "#f5f6f7"

!$RedoxGreen = "#00b388"
!$RedoxBlue = "#5e6ba4"
!$RedoxRed = "#dc5034"
!$RedoxNavy = "#2c314a"
!$RedoxTeal = "#054d55"
!$RedoxCoral = "#f7b6ab"

!$RedoxYellow = "#ffae03"

!$RedoxGreenWhite = "#f6fbfa"

!$RedoxMint = "#85d2c0"
!$RedoxLime = "#c0e75a"

!$RedoxMint1 = "#226265"
!$RedoxMint2 = "#3c7e7c"
!$RedoxMint3 = $RedoxMint
!$RedoxMint4 = "#c4e9e0"
!$RedoxMint5 = "#9bb8bb"

!$RedoxGreen1 = "#008162"
!$RedoxGreen2 = "#009773"
!$RedoxGreen3 = $RedoxGreen
!$RedoxGreen4 = "#00cc9b"
!$RedoxGreen5 = "#00e3ac"

!$RedoxBlue1 = "#485176"
!$RedoxBlue2 = "#515c8e"
!$RedoxBlue3 = $RedoxBlue
!$RedoxBlue4 = "#6d7dc3"
!$RedoxBlue5 = "#7586ce"

!$RedoxRed1 = "#a43a25"
!$RedoxRed2 = "#c0462d"
!$RedoxRed3 = $RedoxRed
!$RedoxRed4 = "#e6654d"
!$RedoxRed5 = "#ef826c"

!$CanvasColor = $RedoxGrey4
!$FillColor = $RedoxGreen
!$FillColorAlt = $RedoxMint3
!$TextOverFillColor = $RedoxGreenWhite
!$TextOverFillColorAlt = $RedoxGreen1
!$TextOverBackgroundColor = $RedoxBlue2
!$LinesOverFillColor = $RedoxTeal
!$LinesOverFillColorAlt = $RedoxRed
!$LinesOverBackgroundColor = $RedoxRed

skinparam BackgroundColor $CanvasColor
skinparam DefaultFontColor $TextOverFillColor
skinparam TitleFontColor $TextOverBackgroundColor
skinparam ArrowColor $LinesOverBackgroundColor
skinparam ArrowFontColor $TextOverBackgroundColor

skinparam activity {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam participant {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam state {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam note {
  BackgroundColor $FillColorAlt
  BorderColor $LinesOverFillColorAlt
  FontColor $TextOverFillColorAlt
}

skinparam actor {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverBackgroundColor
}

skinparam agent {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam artifact {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam boundary {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverBackgroundColor
}

skinparam card {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam cloud {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam component {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam control {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverBackgroundColor
}

skinparam database {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam entity {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverBackgroundColor
}

skinparam file {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam folder {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam frame {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam interface {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverBackgroundColor
}

skinparam node {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam package {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam queue {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam stack {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam rectangle {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam storage {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

skinparam usecase {
  BackgroundColor $FillColor
  BorderColor $LinesOverFillColor
  FontColor $TextOverFillColor
}

@enduml